// UI primitives barrel (D8) — exports added per slice (2a: Button, IconButton; 2b: Card, Badge; 2c: Input, SearchInput).
export { Button } from './Button'
export type { ButtonProps, ButtonSize, ButtonVariant } from './Button'
export { IconButton } from './IconButton'
export type { IconButtonProps } from './IconButton'
export { Card } from './Card'
export type { CardProps, CardVariant } from './Card'
export { Badge } from './Badge'
export type { BadgeProps, BadgeTone } from './Badge'
export { Input } from './Input'
export type { InputProps } from './Input'
export { SearchInput } from './SearchInput'
export type { SearchInputProps } from './SearchInput'
